# Copyright (c) 2024-2025, NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED.
#
# SPDX-License-Identifier: Apache-2.0

MD013:
  line_length: 92
  code_block_line_length: 88
  code_blocks: true
  tables: false
  stern: true
MD033:
  allowed_elements:
    - img
    - h1
