// Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED.
//
// SPDX-License-Identifier: Apache-2.0

#ifndef NVMATH_NDBUFFER_CONSTS_H
#define NVMATH_NDBUFFER_CONSTS_H

#define NDBUFFER_MAX_NDIM 32
#define NDBUFFER_CPU_DEVICE_ID -1

#endif // NVMATH_NDBUFFER_CONSTS_H
