# Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED.
#
# SPDX-License-Identifier: Apache-2.0

import _cython_3_2_4
import enum
from typing import Any, Callable, ClassVar

__pyx_capi__: dict
__test__: dict
check_status: _cython_3_2_4.cython_function_or_method
commondx_create_code: _cython_3_2_4.cython_function_or_method
commondx_destroy_code: _cython_3_2_4.cython_function_or_method
commondx_get_code_ltoir: _cython_3_2_4.cython_function_or_method
commondx_get_code_ltoir_size: _cython_3_2_4.cython_function_or_method
commondx_get_code_ltoir_sizes: _cython_3_2_4.cython_function_or_method
commondx_get_code_ltoirs: _cython_3_2_4.cython_function_or_method
commondx_get_code_num_ltoirs: _cython_3_2_4.cython_function_or_method
commondx_get_code_option_int64: _cython_3_2_4.cython_function_or_method
commondx_get_code_options_int64s: _cython_3_2_4.cython_function_or_method
commondx_get_code_ptx: _cython_3_2_4.cython_function_or_method
commondx_get_code_ptx_size: _cython_3_2_4.cython_function_or_method
commondx_set_code_option_int64: _cython_3_2_4.cython_function_or_method
commondx_set_code_option_int64s: _cython_3_2_4.cython_function_or_method
commondx_set_code_option_str: _cython_3_2_4.cython_function_or_method
commondx_status_to_str: _cython_3_2_4.cython_function_or_method
cublasdx_create_descriptor: _cython_3_2_4.cython_function_or_method
cublasdx_create_device_function: _cython_3_2_4.cython_function_or_method
cublasdx_create_device_function_with_pipelines: _cython_3_2_4.cython_function_or_method
cublasdx_create_device_pipeline: _cython_3_2_4.cython_function_or_method
cublasdx_create_tensor: _cython_3_2_4.cython_function_or_method
cublasdx_create_tensor_strided: _cython_3_2_4.cython_function_or_method
cublasdx_create_tile_pipeline: _cython_3_2_4.cython_function_or_method
cublasdx_destroy_descriptor: _cython_3_2_4.cython_function_or_method
cublasdx_destroy_device_function: _cython_3_2_4.cython_function_or_method
cublasdx_destroy_pipeline: _cython_3_2_4.cython_function_or_method
cublasdx_destroy_tensor: _cython_3_2_4.cython_function_or_method
cublasdx_finalize: _cython_3_2_4.cython_function_or_method
cublasdx_finalize_code: _cython_3_2_4.cython_function_or_method
cublasdx_finalize_device_functions: _cython_3_2_4.cython_function_or_method
cublasdx_finalize_pipelines: _cython_3_2_4.cython_function_or_method
cublasdx_finalize_tensors: _cython_3_2_4.cython_function_or_method
cublasdx_get_device_function_trait_str: _cython_3_2_4.cython_function_or_method
cublasdx_get_device_function_trait_str_size: _cython_3_2_4.cython_function_or_method
cublasdx_get_ltoir: _cython_3_2_4.cython_function_or_method
cublasdx_get_ltoir_size: _cython_3_2_4.cython_function_or_method
cublasdx_get_pipeline_trait_int64: _cython_3_2_4.cython_function_or_method
cublasdx_get_pipeline_trait_int64s: _cython_3_2_4.cython_function_or_method
cublasdx_get_pipeline_trait_str: _cython_3_2_4.cython_function_or_method
cublasdx_get_pipeline_trait_str_size: _cython_3_2_4.cython_function_or_method
cublasdx_get_tensor_trait_int64: _cython_3_2_4.cython_function_or_method
cublasdx_get_tensor_trait_str: _cython_3_2_4.cython_function_or_method
cublasdx_get_tensor_trait_str_size: _cython_3_2_4.cython_function_or_method
cublasdx_get_trait_int64: _cython_3_2_4.cython_function_or_method
cublasdx_get_trait_int64s: _cython_3_2_4.cython_function_or_method
cublasdx_get_trait_str: _cython_3_2_4.cython_function_or_method
cublasdx_get_trait_str_size: _cython_3_2_4.cython_function_or_method
cublasdx_make_tensor_like: _cython_3_2_4.cython_function_or_method
cublasdx_operator_type_to_str: _cython_3_2_4.cython_function_or_method
cublasdx_set_operator_int64: _cython_3_2_4.cython_function_or_method
cublasdx_set_operator_int64s: _cython_3_2_4.cython_function_or_method
cublasdx_set_option_str: _cython_3_2_4.cython_function_or_method
cublasdx_set_tensor_option_int64: _cython_3_2_4.cython_function_or_method
cublasdx_trait_type_to_str: _cython_3_2_4.cython_function_or_method
cufftdx_create_descriptor: _cython_3_2_4.cython_function_or_method
cufftdx_destroy_descriptor: _cython_3_2_4.cython_function_or_method
cufftdx_finalize_code: _cython_3_2_4.cython_function_or_method
cufftdx_get_knob_int64s: _cython_3_2_4.cython_function_or_method
cufftdx_get_knob_int64size: _cython_3_2_4.cython_function_or_method
cufftdx_get_ltoir: _cython_3_2_4.cython_function_or_method
cufftdx_get_ltoir_size: _cython_3_2_4.cython_function_or_method
cufftdx_get_trait_commondx_data_type: _cython_3_2_4.cython_function_or_method
cufftdx_get_trait_int64: _cython_3_2_4.cython_function_or_method
cufftdx_get_trait_int64s: _cython_3_2_4.cython_function_or_method
cufftdx_get_trait_str: _cython_3_2_4.cython_function_or_method
cufftdx_get_trait_str_size: _cython_3_2_4.cython_function_or_method
cufftdx_operator_type_to_str: _cython_3_2_4.cython_function_or_method
cufftdx_set_operator_int64: _cython_3_2_4.cython_function_or_method
cufftdx_set_operator_int64s: _cython_3_2_4.cython_function_or_method
cufftdx_set_option_str: _cython_3_2_4.cython_function_or_method
cufftdx_trait_type_to_str: _cython_3_2_4.cython_function_or_method
curanddx_create_descriptor: _cython_3_2_4.cython_function_or_method
curanddx_destroy_descriptor: _cython_3_2_4.cython_function_or_method
curanddx_distribution_to_str: _cython_3_2_4.cython_function_or_method
curanddx_finalize_code: _cython_3_2_4.cython_function_or_method
curanddx_generate_method_to_str: _cython_3_2_4.cython_function_or_method
curanddx_generator_to_str: _cython_3_2_4.cython_function_or_method
curanddx_get_trait_int64: _cython_3_2_4.cython_function_or_method
curanddx_get_trait_str: _cython_3_2_4.cython_function_or_method
curanddx_get_trait_str_size: _cython_3_2_4.cython_function_or_method
curanddx_get_version: _cython_3_2_4.cython_function_or_method
curanddx_normal_method_to_str: _cython_3_2_4.cython_function_or_method
curanddx_operator_type_to_str: _cython_3_2_4.cython_function_or_method
curanddx_set_operator_doubles: _cython_3_2_4.cython_function_or_method
curanddx_set_operator_int64: _cython_3_2_4.cython_function_or_method
curanddx_set_option_str: _cython_3_2_4.cython_function_or_method
curanddx_trait_type_to_str: _cython_3_2_4.cython_function_or_method
cusolverdx_create_descriptor: _cython_3_2_4.cython_function_or_method
cusolverdx_destroy_descriptor: _cython_3_2_4.cython_function_or_method
cusolverdx_finalize_code: _cython_3_2_4.cython_function_or_method
cusolverdx_get_ltoir: _cython_3_2_4.cython_function_or_method
cusolverdx_get_ltoir_size: _cython_3_2_4.cython_function_or_method
cusolverdx_get_trait_commondx_data_types: _cython_3_2_4.cython_function_or_method
cusolverdx_get_trait_int64: _cython_3_2_4.cython_function_or_method
cusolverdx_get_trait_int64s: _cython_3_2_4.cython_function_or_method
cusolverdx_get_trait_str: _cython_3_2_4.cython_function_or_method
cusolverdx_get_trait_str_size: _cython_3_2_4.cython_function_or_method
cusolverdx_get_universal_fatbin: _cython_3_2_4.cython_function_or_method
cusolverdx_get_universal_fatbin_size: _cython_3_2_4.cython_function_or_method
cusolverdx_operator_type_to_str: _cython_3_2_4.cython_function_or_method
cusolverdx_set_operator_int64: _cython_3_2_4.cython_function_or_method
cusolverdx_set_operator_int64s: _cython_3_2_4.cython_function_or_method
cusolverdx_set_option_str: _cython_3_2_4.cython_function_or_method
cusolverdx_trait_type_to_str: _cython_3_2_4.cython_function_or_method
get_version: _cython_3_2_4.cython_function_or_method
get_version_ex: _cython_3_2_4.cython_function_or_method

class CommondxArchModifier(enum.IntEnum):
    """
    The set of compute feature to target. See COMMONDX_OPTION_TARGET_SM
    .See also https://docs.nvidia.com/cuda/cuda-c-programming-
    guide/index.html#feature-set-compiler-targets

    See `commondxArchModifier`.
    """
    __new__: ClassVar[Callable] = ...
    ARCH_SPECIFIC: ClassVar[CommondxArchModifier] = ...
    FAMILY_SPECIFIC: ClassVar[CommondxArchModifier] = ...
    GENERIC: ClassVar[CommondxArchModifier] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CommondxCodeContainer(enum.IntEnum):
    """
    The set of device code container types supported by the library. See
    commondxOption_t::COMMONDX_OPTION_CODE_CONTAINER.

    See `commondxCodeContainer`.
    """
    __new__: ClassVar[Callable] = ...
    FATBIN: ClassVar[CommondxCodeContainer] = ...
    LTOIR: ClassVar[CommondxCodeContainer] = ...
    PTX: ClassVar[CommondxCodeContainer] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CommondxCodeType(enum.IntEnum):
    """
    The set of code types supported by the library. See
    commondxOption_t::COMMONDX_OPTION_TARGET_CODE.

    See `commondxCodeType`.
    """
    __new__: ClassVar[Callable] = ...
    LTO: ClassVar[CommondxCodeType] = ...
    PTX: ClassVar[CommondxCodeType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CommondxExecution(enum.IntEnum):
    """
    The set of execution modes supported by the library.

    See `commondxExecution`.
    """
    __new__: ClassVar[Callable] = ...
    BLOCK: ClassVar[CommondxExecution] = ...
    THREAD: ClassVar[CommondxExecution] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CommondxOption(enum.IntEnum):
    """
    Options to tweak code generation.

    See `commondxOption`.
    """
    __new__: ClassVar[Callable] = ...
    CODE_CONTAINER: ClassVar[CommondxOption] = ...
    CODE_ISA: ClassVar[CommondxOption] = ...
    EXTRA_NVRTC_ARGS: ClassVar[CommondxOption] = ...
    SYMBOL_NAME: ClassVar[CommondxOption] = ...
    TARGET_CODE: ClassVar[CommondxOption] = ...
    TARGET_SM: ClassVar[CommondxOption] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CommondxPrecision(enum.IntEnum):
    """
    The set of precisions supported by the library.For the actual input and
    output value types, see commondxValueType_t

    See `commondxPrecision`.
    """
    __new__: ClassVar[Callable] = ...
    BF16: ClassVar[CommondxPrecision] = ...
    F16: ClassVar[CommondxPrecision] = ...
    F32: ClassVar[CommondxPrecision] = ...
    F64: ClassVar[CommondxPrecision] = ...
    F8_E4M3: ClassVar[CommondxPrecision] = ...
    F8_E5M2: ClassVar[CommondxPrecision] = ...
    I16: ClassVar[CommondxPrecision] = ...
    I32: ClassVar[CommondxPrecision] = ...
    I64: ClassVar[CommondxPrecision] = ...
    I8: ClassVar[CommondxPrecision] = ...
    TF32: ClassVar[CommondxPrecision] = ...
    UI16: ClassVar[CommondxPrecision] = ...
    UI32: ClassVar[CommondxPrecision] = ...
    UI64: ClassVar[CommondxPrecision] = ...
    UI8: ClassVar[CommondxPrecision] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CommondxStatusType(enum.IntEnum):
    """
    The set of status values that can be returned by APIs defined in the
    library.

    See `commondxStatusType`.
    """
    __new__: ClassVar[Callable] = ...
    COMPILATION_ERROR: ClassVar[CommondxStatusType] = ...
    CUFFT_ERROR: ClassVar[CommondxStatusType] = ...
    INTERNAL_ERROR: ClassVar[CommondxStatusType] = ...
    INVALID_VALUE: ClassVar[CommondxStatusType] = ...
    SUCCESS: ClassVar[CommondxStatusType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CommondxValueType(enum.IntEnum):
    """
    The set of value types supported by the library.Note that, for complex
    numbers, this combines real and imaginary part, and that all complex
    numbers are overaligned on their size.

    See `commondxValueType`.
    """
    __new__: ClassVar[Callable] = ...
    C_16BF: ClassVar[CommondxValueType] = ...
    C_16F: ClassVar[CommondxValueType] = ...
    C_16F2: ClassVar[CommondxValueType] = ...
    C_16I: ClassVar[CommondxValueType] = ...
    C_16UI: ClassVar[CommondxValueType] = ...
    C_32F: ClassVar[CommondxValueType] = ...
    C_32I: ClassVar[CommondxValueType] = ...
    C_32TF: ClassVar[CommondxValueType] = ...
    C_32UI: ClassVar[CommondxValueType] = ...
    C_64F: ClassVar[CommondxValueType] = ...
    C_64I: ClassVar[CommondxValueType] = ...
    C_64UI: ClassVar[CommondxValueType] = ...
    C_8F_E4M3: ClassVar[CommondxValueType] = ...
    C_8F_E5M2: ClassVar[CommondxValueType] = ...
    C_8I: ClassVar[CommondxValueType] = ...
    C_8UI: ClassVar[CommondxValueType] = ...
    R_16BF: ClassVar[CommondxValueType] = ...
    R_16F: ClassVar[CommondxValueType] = ...
    R_16F2: ClassVar[CommondxValueType] = ...
    R_16I: ClassVar[CommondxValueType] = ...
    R_16UI: ClassVar[CommondxValueType] = ...
    R_32F: ClassVar[CommondxValueType] = ...
    R_32I: ClassVar[CommondxValueType] = ...
    R_32TF: ClassVar[CommondxValueType] = ...
    R_32UI: ClassVar[CommondxValueType] = ...
    R_64F: ClassVar[CommondxValueType] = ...
    R_64I: ClassVar[CommondxValueType] = ...
    R_64UI: ClassVar[CommondxValueType] = ...
    R_8F_E4M3: ClassVar[CommondxValueType] = ...
    R_8F_E5M2: ClassVar[CommondxValueType] = ...
    R_8I: ClassVar[CommondxValueType] = ...
    R_8UI: ClassVar[CommondxValueType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CublasdxApi(enum.IntEnum):
    """
    Type of cublasDx API.Handling problems with default or custom/dynamic
    leading dimensions. Check cublasdx::LeadingDimension operator
    documentation for more details (https://docs.nvidia.com/cuda/cublasdx/a
    pi/operators.html#leadingdimension-operator)

    See `cublasdxApi`.
    """
    __new__: ClassVar[Callable] = ...
    SMEM: ClassVar[CublasdxApi] = ...
    SMEM_DYNAMIC_LD: ClassVar[CublasdxApi] = ...
    TENSORS: ClassVar[CublasdxApi] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CublasdxArrangement(enum.IntEnum):
    """
    Data arrangement mode.Defines data arrangements in tensors' taking part
    in the calculation.  Check cubladx::TransposeMode operator
    documentation for more details
    (https://docs.nvidia.com/cuda/cublasdx/api/operators.html#arrangement-
    operator)

    See `cublasdxArrangement`.
    """
    __new__: ClassVar[Callable] = ...
    COL_MAJOR: ClassVar[CublasdxArrangement] = ...
    ROW_MAJOR: ClassVar[CublasdxArrangement] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CublasdxBlockSizeStrategy(enum.IntEnum):
    """
    Type of block size strategy used in device pipeline and tile pipeline
    creation. This enum affects register usage in pipelining GEMM kernels
    and should be considered for different architectures.

    See `cublasdxBlockSizeStrategy`.
    """
    __new__: ClassVar[Callable] = ...
    FIXED: ClassVar[CublasdxBlockSizeStrategy] = ...
    HEURISTIC: ClassVar[CublasdxBlockSizeStrategy] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CublasdxDeviceFunctionOption(enum.IntEnum):
    """
    Device function options.

    See `cublasdxDeviceFunctionOption`.
    """
    __new__: ClassVar[Callable] = ...
    CALLBACK: ClassVar[CublasdxDeviceFunctionOption] = ...
    COPY_ALIGNMENT: ClassVar[CublasdxDeviceFunctionOption] = ...
    NUM_THREADS: ClassVar[CublasdxDeviceFunctionOption] = ...
    SYMBOL_NAME: ClassVar[CublasdxDeviceFunctionOption] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CublasdxDeviceFunctionTrait(enum.IntEnum):
    """
    Device function traits, used to query informations.

    See `cublasdxDeviceFunctionTrait`.
    """
    __new__: ClassVar[Callable] = ...
    SYMBOL: ClassVar[CublasdxDeviceFunctionTrait] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CublasdxDeviceFunctionType(enum.IntEnum):
    """
    Device functions supported by the library.

    See `cublasdxDeviceFunctionType`.
    """
    __new__: ClassVar[Callable] = ...
    AXPBY: ClassVar[CublasdxDeviceFunctionType] = ...
    CLEAR: ClassVar[CublasdxDeviceFunctionType] = ...
    COPY: ClassVar[CublasdxDeviceFunctionType] = ...
    COPY_WAIT: ClassVar[CublasdxDeviceFunctionType] = ...
    CREATE: ClassVar[CublasdxDeviceFunctionType] = ...
    DESTROY: ClassVar[CublasdxDeviceFunctionType] = ...
    EPILOGUE: ClassVar[CublasdxDeviceFunctionType] = ...
    EXECUTE: ClassVar[CublasdxDeviceFunctionType] = ...
    IS_INDEX_IN_BOUNDS: ClassVar[CublasdxDeviceFunctionType] = ...
    IS_PREDICATED: ClassVar[CublasdxDeviceFunctionType] = ...
    IS_THREAD_ACTIVE: ClassVar[CublasdxDeviceFunctionType] = ...
    MAP_CRD2IDX: ClassVar[CublasdxDeviceFunctionType] = ...
    MAP_IDX2CRD: ClassVar[CublasdxDeviceFunctionType] = ...
    MAP_IDX2CRD_PARTITIONER: ClassVar[CublasdxDeviceFunctionType] = ...
    RESET: ClassVar[CublasdxDeviceFunctionType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CublasdxDevicePipelineType(enum.IntEnum):
    """
    Type of device pipeline.

    See `cublasdxDevicePipelineType`.
    """
    __new__: ClassVar[Callable] = ...
    SUGGESTED: ClassVar[CublasdxDevicePipelineType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CublasdxFunction(enum.IntEnum):
    """
    BLAS function.Sets the BLAS function that will be executed.  Check
    cubladx::Function operator documentation for more details
    (https://docs.nvidia.com/cuda/cublasdx/api/operators.html#function-
    operator)

    See `cublasdxFunction`.
    """
    __new__: ClassVar[Callable] = ...
    MM: ClassVar[CublasdxFunction] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CublasdxMemorySpace(enum.IntEnum):
    """
    Memory space.

    See `cublasdxMemorySpace`.
    """
    __new__: ClassVar[Callable] = ...
    ANY: ClassVar[CublasdxMemorySpace] = ...
    GMEM: ClassVar[CublasdxMemorySpace] = ...
    RMEM: ClassVar[CublasdxMemorySpace] = ...
    SMEM: ClassVar[CublasdxMemorySpace] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CublasdxOperatorType(enum.IntEnum):
    """
    cublasDx operatorsThe set of supported cublasDx operators.  Check
    cublaDx description operator documentation for more details
    (https://docs.nvidia.com/cuda/cublasdx/api/operators.html#function-
    operator)  Check cublasDx execution operator documentation for more
    details
    (https://docs.nvidia.com/cuda/cublasdx/api/operators.html#execution-
    operators)

    See `cublasdxOperatorType`.
    """
    __new__: ClassVar[Callable] = ...
    ALIGNMENT: ClassVar[CublasdxOperatorType] = ...
    API: ClassVar[CublasdxOperatorType] = ...
    ARRANGEMENT: ClassVar[CublasdxOperatorType] = ...
    BLOCK_DIM: ClassVar[CublasdxOperatorType] = ...
    ENABLE_INPUT_STREAMING: ClassVar[CublasdxOperatorType] = ...
    EXECUTION: ClassVar[CublasdxOperatorType] = ...
    FUNCTION: ClassVar[CublasdxOperatorType] = ...
    LEADING_DIMENSION: ClassVar[CublasdxOperatorType] = ...
    PRECISION: ClassVar[CublasdxOperatorType] = ...
    SIZE: ClassVar[CublasdxOperatorType] = ...
    SM: ClassVar[CublasdxOperatorType] = ...
    STATIC_BLOCK_DIM: ClassVar[CublasdxOperatorType] = ...
    TRANSPOSE_MODE: ClassVar[CublasdxOperatorType] = ...
    TYPE: ClassVar[CublasdxOperatorType] = ...
    WITH_PIPELINE: ClassVar[CublasdxOperatorType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CublasdxPipelineTrait(enum.IntEnum):
    """
    Pipeline traits, used to query informations.

    See `cublasdxPipelineTrait`.
    """
    __new__: ClassVar[Callable] = ...
    BLOCK_DIM: ClassVar[CublasdxPipelineTrait] = ...
    BUFFER_ALIGNMENT_BYTES: ClassVar[CublasdxPipelineTrait] = ...
    BUFFER_SIZE: ClassVar[CublasdxPipelineTrait] = ...
    OPAQUE_NAME: ClassVar[CublasdxPipelineTrait] = ...
    STORAGE_ALIGNMENT_BYTES: ClassVar[CublasdxPipelineTrait] = ...
    STORAGE_BYTES: ClassVar[CublasdxPipelineTrait] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CublasdxTensorOption(enum.IntEnum):
    """
    Tensor options.

    See `cublasdxTensorOption`.
    """
    __new__: ClassVar[Callable] = ...
    ALIGNMENT_BYTES: ClassVar[CublasdxTensorOption] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CublasdxTensorTrait(enum.IntEnum):
    """
    Tensor traits, used to query informations.

    See `cublasdxTensorTrait`.
    """
    __new__: ClassVar[Callable] = ...
    ALIGNMENT_BYTES: ClassVar[CublasdxTensorTrait] = ...
    LOGICAL_SIZE: ClassVar[CublasdxTensorTrait] = ...
    MEMORY_SPACE: ClassVar[CublasdxTensorTrait] = ...
    OPAQUE_NAME: ClassVar[CublasdxTensorTrait] = ...
    STORAGE_BYTES: ClassVar[CublasdxTensorTrait] = ...
    UID: ClassVar[CublasdxTensorTrait] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CublasdxTensorType(enum.IntEnum):
    """
    cuBLASDx desired tensor typeTensor types are opaque (layout is
    unspecified), non-owning, and defined by  - Memory space (global,
    shared or register memory)  - Size & alignment (in bytes)  Tensor's
    representation in-memory and in-device depends on their memory space.
    Shared & register tensors are defined as  **View CUDA Toolkit
    Documentation for a C++ code example**  where `ptr` points to the
    associated data.  Global memory tensors have an associated runtime
    leading dimension (64b signed integer), and their representation is
    **View CUDA Toolkit Documentation for a C++ code example**  where `ptr`
    points to the associated data and `strides[0]` is the leading
    dimension.  In either case, `ptr` must point to some storage (with
    appropriate size and alignment, see below) and is not owning. The user
    is expected to keep memory allocated beyond any use of the tensor.
    `strides[1]` should be a signed, 64bit integer (`long long`) equal to
    the leading dimension of the global memory tensor. The leading
    dimension is the number of `elements` between two successive rows or
    columns (not bytes), depending on the context.  All tensor APIs take
    their argument by value (not by pointer) and expect the struct to be
    passed as-is on the stack.  Each opaque tensor type is uniquely
    identified by a unique ID and name, see cublasdxTensorTrait_t .

    See `cublasdxTensorType`.
    """
    __new__: ClassVar[Callable] = ...
    ACCUMULATOR_C: ClassVar[CublasdxTensorType] = ...
    GMEM_A: ClassVar[CublasdxTensorType] = ...
    GMEM_B: ClassVar[CublasdxTensorType] = ...
    GMEM_C: ClassVar[CublasdxTensorType] = ...
    RMEM_C: ClassVar[CublasdxTensorType] = ...
    SMEM_A: ClassVar[CublasdxTensorType] = ...
    SMEM_B: ClassVar[CublasdxTensorType] = ...
    SMEM_C: ClassVar[CublasdxTensorType] = ...
    SUGGESTED_ACCUMULATOR_C: ClassVar[CublasdxTensorType] = ...
    SUGGESTED_RMEM_C: ClassVar[CublasdxTensorType] = ...
    SUGGESTED_SMEM_A: ClassVar[CublasdxTensorType] = ...
    SUGGESTED_SMEM_B: ClassVar[CublasdxTensorType] = ...
    SUGGESTED_SMEM_C: ClassVar[CublasdxTensorType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CublasdxTilePipelineType(enum.IntEnum):
    """
    Type of tile pipeline.

    See `cublasdxTilePipelineType`.
    """
    __new__: ClassVar[Callable] = ...
    PIPELINE_DEFAULT: ClassVar[CublasdxTilePipelineType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CublasdxTraitType(enum.IntEnum):
    """
    cublasDx traitsThe set of supported types of traits that can be
    accessed from finalized sources that use cublasDx.  Check cublasDx
    Execution Block Traits documentation for more details
    (https://docs.nvidia.com/cuda/cublasdx/api/traits.html#block-traits)

    See `cublasdxTraitType`.
    """
    __new__: ClassVar[Callable] = ...
    ALIGNMENT: ClassVar[CublasdxTraitType] = ...
    ARRANGEMENT: ClassVar[CublasdxTraitType] = ...
    BLOCK_DIM: ClassVar[CublasdxTraitType] = ...
    BLOCK_SIZE: ClassVar[CublasdxTraitType] = ...
    LEADING_DIMENSION: ClassVar[CublasdxTraitType] = ...
    MAX_THREADS_PER_BLOCK: ClassVar[CublasdxTraitType] = ...
    SIZE: ClassVar[CublasdxTraitType] = ...
    SUGGESTED_BLOCK_DIM: ClassVar[CublasdxTraitType] = ...
    SUGGESTED_LEADING_DIMENSION: ClassVar[CublasdxTraitType] = ...
    SYMBOL_NAME: ClassVar[CublasdxTraitType] = ...
    VALUE_TYPE: ClassVar[CublasdxTraitType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CublasdxTransposeMode(enum.IntEnum):
    """
    Tensor transpose mode.The transpose mode depends on
    cubladx::TransposeMode operator which is deprecated since cublasDx
    0.2.0 and might be removed in future versions of mathDx libraries
    Check cubladx::TransposeMode operator documentation for more details (h
    ttps://docs.nvidia.com/cuda/cublasdx/api/operators.html#transposemode-
    operator)

    See `cublasdxTransposeMode`.
    """
    __new__: ClassVar[Callable] = ...
    CONJ_TRANSPOSED: ClassVar[CublasdxTransposeMode] = ...
    NON_TRANSPOSED: ClassVar[CublasdxTransposeMode] = ...
    TRANSPOSED: ClassVar[CublasdxTransposeMode] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CublasdxType(enum.IntEnum):
    """
    Type of computation data.Check cubladx::Type operator documentation for
    more details
    (https://docs.nvidia.com/cuda/cublasdx/api/operators.html#type-
    operator)

    See `cublasdxType`.
    """
    __new__: ClassVar[Callable] = ...
    COMPLEX: ClassVar[CublasdxType] = ...
    REAL: ClassVar[CublasdxType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CufftdxApi(enum.IntEnum):
    """
    Type of cufftDx API.Handling problems with input in register or in
    shared memory buffers.  Check cufftdx::execute method documentation for
    more details
    (https://docs.nvidia.com/cuda/cufftdx/api/methods.html#block-execute-
    method)

    See `cufftdxApi`.
    """
    __new__: ClassVar[Callable] = ...
    LMEM: ClassVar[CufftdxApi] = ...
    SMEM: ClassVar[CufftdxApi] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CufftdxCodeType(enum.IntEnum):
    """
    Code type.Check cufftdx code type documentation for more details
    (https://docs.nvidia.com/cuda/1.4.0-ea/cufftdx/api/methods.html#code-
    type)

    See `cufftdxCodeType`.
    """
    __new__: ClassVar[Callable] = ...
    LTOIR: ClassVar[CufftdxCodeType] = ...
    PTX: ClassVar[CufftdxCodeType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CufftdxComplexLayout(enum.IntEnum):
    """
    Complex data layout.Check cufftdx layout documentation for more details
    (https://docs.nvidia.com/cuda/cufftdx/api/methods.html#complex-element-
    layouts)

    See `cufftdxComplexLayout`.
    """
    __new__: ClassVar[Callable] = ...
    FULL: ClassVar[CufftdxComplexLayout] = ...
    NATURAL: ClassVar[CufftdxComplexLayout] = ...
    PACKED: ClassVar[CufftdxComplexLayout] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CufftdxDirection(enum.IntEnum):
    """
    FFT direction.Check cufftdx::Direction operator documentation for more
    details
    (https://docs.nvidia.com/cuda/cufftdx/api/operators.html#direction-
    operator)

    See `cufftdxDirection`.
    """
    __new__: ClassVar[Callable] = ...
    FORWARD: ClassVar[CufftdxDirection] = ...
    INVERSE: ClassVar[CufftdxDirection] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CufftdxKnobType(enum.IntEnum):
    """
    cufftDx configuration knobsThe set of supported knobs used for
    accessing cufftDx operator's performance configuration details.  Check
    cufftDx Execution Traits documentation for more details
    (https://docs.nvidia.com/cuda/cufftdx/api/traits.html#execution-traits)

    See `cufftdxKnobType`.
    """
    __new__: ClassVar[Callable] = ...
    ELEMENTS_PER_THREAD: ClassVar[CufftdxKnobType] = ...
    FFTS_PER_BLOCK: ClassVar[CufftdxKnobType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CufftdxOperatorType(enum.IntEnum):
    """
    cufftDx operatorsThe set of supported cufftDx operators.  Check cufftDx
    description operators documentation for more details
    (https://docs.nvidia.com/cuda/cufftdx/api/operators.html#description-
    operators)  Check cufftDx execution operators documentation for more
    details
    (https://docs.nvidia.com/cuda/cufftdx/api/operators.html#execution-
    operators)

    See `cufftdxOperatorType`.
    """
    __new__: ClassVar[Callable] = ...
    API: ClassVar[CufftdxOperatorType] = ...
    BLOCK_DIM: ClassVar[CufftdxOperatorType] = ...
    CODE_TYPE: ClassVar[CufftdxOperatorType] = ...
    DIRECTION: ClassVar[CufftdxOperatorType] = ...
    ELEMENTS_PER_THREAD: ClassVar[CufftdxOperatorType] = ...
    EXECUTION: ClassVar[CufftdxOperatorType] = ...
    FFTS_PER_BLOCK: ClassVar[CufftdxOperatorType] = ...
    PRECISION: ClassVar[CufftdxOperatorType] = ...
    REAL_FFT_OPTIONS: ClassVar[CufftdxOperatorType] = ...
    SIZE: ClassVar[CufftdxOperatorType] = ...
    SM: ClassVar[CufftdxOperatorType] = ...
    TYPE: ClassVar[CufftdxOperatorType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CufftdxRealMode(enum.IntEnum):
    """
    Real data mode.Check cufftdx real data mode documentation for more
    details (https://docs.nvidia.com/cuda/cufftdx/api/methods.html#real-
    element-layouts)

    See `cufftdxRealMode`.
    """
    __new__: ClassVar[Callable] = ...
    FOLDED: ClassVar[CufftdxRealMode] = ...
    NORMAL: ClassVar[CufftdxRealMode] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CufftdxTraitType(enum.IntEnum):
    """
    cufftDx traitsThe set of supported types of traits that can be accessed
    from finalized sources that use cufftDx.  Check cufftDx Execution
    Thread Traits documentation for more details
    (https://docs.nvidia.com/cuda/cufftdx/api/traits.html#thread-traits)
    Check cufftDx Execution Block Traits documentation for more details
    (https://docs.nvidia.com/cuda/cufftdx/api/traits.html#block-traits)

    See `cufftdxTraitType`.
    """
    __new__: ClassVar[Callable] = ...
    BLOCK_DIM: ClassVar[CufftdxTraitType] = ...
    ELEMENTS_PER_THREAD: ClassVar[CufftdxTraitType] = ...
    FFTS_PER_BLOCK: ClassVar[CufftdxTraitType] = ...
    IMPLICIT_TYPE_BATCHING: ClassVar[CufftdxTraitType] = ...
    INPUT_ELEMENTS_PER_THREAD: ClassVar[CufftdxTraitType] = ...
    INPUT_LENGTH: ClassVar[CufftdxTraitType] = ...
    INPUT_TYPE: ClassVar[CufftdxTraitType] = ...
    OUTPUT_ELEMENTS_PER_THREAD: ClassVar[CufftdxTraitType] = ...
    OUTPUT_LENGTH: ClassVar[CufftdxTraitType] = ...
    OUTPUT_TYPE: ClassVar[CufftdxTraitType] = ...
    SHARED_MEMORY_SIZE: ClassVar[CufftdxTraitType] = ...
    STORAGE_SIZE: ClassVar[CufftdxTraitType] = ...
    STRIDE: ClassVar[CufftdxTraitType] = ...
    SUGGESTED_FFTS_PER_BLOCK: ClassVar[CufftdxTraitType] = ...
    SYMBOL_NAME: ClassVar[CufftdxTraitType] = ...
    VALUE_TYPE: ClassVar[CufftdxTraitType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CufftdxType(enum.IntEnum):
    """
    Type of computation data.Check cufftdx::Type operator documentation for
    more details
    (https://docs.nvidia.com/cuda/cufftdx/api/methods.html#block-execute-
    method)

    See `cufftdxType`.
    """
    __new__: ClassVar[Callable] = ...
    C2C: ClassVar[CufftdxType] = ...
    C2R: ClassVar[CufftdxType] = ...
    R2C: ClassVar[CufftdxType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CuranddxDeviceFunctionType(enum.IntEnum):
    """
    Device functions.The set of supported device functions. Must be passed
    using CURANDDX_OPERATOR_DEVICE_FUNCTIONS and can be or'ed to indicate
    that libmathdx should generate multiple device functions.

    See `curanddxDeviceFunctionType`.
    """
    __new__: ClassVar[Callable] = ...
    DESTROY_STATE: ClassVar[CuranddxDeviceFunctionType] = ...
    GENERATE: ClassVar[CuranddxDeviceFunctionType] = ...
    INIT_STATE: ClassVar[CuranddxDeviceFunctionType] = ...
    SKIP_OFFSET: ClassVar[CuranddxDeviceFunctionType] = ...
    SKIP_SEQUENCE: ClassVar[CuranddxDeviceFunctionType] = ...
    SKIP_SUBSEQUENCE: ClassVar[CuranddxDeviceFunctionType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CuranddxDistribution(enum.IntEnum):
    """
    Distribution type.Indicate the random number generation to use. Can be
    set using CURANDDX_OPERATOR_DISTRIBUTION and further customized using
    CURANDDX_OPERATOR_NORMAL_METHOD. See cuRANDDx distributions in the
    documentation:
    https://docs.nvidia.com/cuda/curanddx/api/methods.html#random-number-
    generation-with-distributions.

    See `curanddxDistribution`.
    """
    __new__: ClassVar[Callable] = ...
    LOG_NORMAL: ClassVar[CuranddxDistribution] = ...
    NORMAL: ClassVar[CuranddxDistribution] = ...
    POISSON: ClassVar[CuranddxDistribution] = ...
    UNIFORM: ClassVar[CuranddxDistribution] = ...
    UNIFORM_BITS: ClassVar[CuranddxDistribution] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CuranddxGenerateMethod(enum.IntEnum):
    """
    Generation method type.Specifies which generation method to use for
    cuRANDDx distributions. Set using CURANDDX_OPERATOR_GENERATE_METHOD .
    See cuRANDDx execution methods in the documentation:
    https://docs.nvidia.com/cuda/curanddx/api/methods.html

    See `curanddxGenerateMethod`.
    """
    __new__: ClassVar[Callable] = ...
    PAIR: ClassVar[CuranddxGenerateMethod] = ...
    QUAD: ClassVar[CuranddxGenerateMethod] = ...
    SINGLE: ClassVar[CuranddxGenerateMethod] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CuranddxGenerator(enum.IntEnum):
    """
    Generator type.Matches cuRANDDx generator kinds. Set using
    CURANDDX_OPERATOR_GENERATOR . See cuRANDDx generators in the
    documentation: https://docs.nvidia.com/cuda/curanddx/api/description_op
    s.html#generator-operator-label

    See `curanddxGenerator`.
    """
    __new__: ClassVar[Callable] = ...
    MRG32K3A: ClassVar[CuranddxGenerator] = ...
    PCG: ClassVar[CuranddxGenerator] = ...
    PHILOX4_32: ClassVar[CuranddxGenerator] = ...
    SCRAMBLED_SOBOL32: ClassVar[CuranddxGenerator] = ...
    SCRAMBLED_SOBOL64: ClassVar[CuranddxGenerator] = ...
    SOBOL32: ClassVar[CuranddxGenerator] = ...
    SOBOL64: ClassVar[CuranddxGenerator] = ...
    XORWOW: ClassVar[CuranddxGenerator] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CuranddxNormalMethod(enum.IntEnum):
    """
    Normal distribution method type.Specifies the method to use for normal
    and log-normal distributions. Set using CURANDDX_OPERATOR_NORMAL_METHOD
    . See cuRANDDx normal distribution documentation:
    https://docs.nvidia.com/cuda/curanddx/api/methods.html#normal-
    distribution

    See `curanddxNormalMethod`.
    """
    __new__: ClassVar[Callable] = ...
    BOX_MULLER: ClassVar[CuranddxNormalMethod] = ...
    ICDF: ClassVar[CuranddxNormalMethod] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CuranddxOperatorType(enum.IntEnum):
    """
    Operators.The set of supported curandDx operators.

    See `curanddxOperatorType`.
    """
    __new__: ClassVar[Callable] = ...
    DEVICE_FUNCTIONS: ClassVar[CuranddxOperatorType] = ...
    DISTRIBUTION: ClassVar[CuranddxOperatorType] = ...
    DISTRIBUTION_PARAMETERS: ClassVar[CuranddxOperatorType] = ...
    EXECUTION: ClassVar[CuranddxOperatorType] = ...
    GENERATE_METHOD: ClassVar[CuranddxOperatorType] = ...
    GENERATOR: ClassVar[CuranddxOperatorType] = ...
    NORMAL_METHOD: ClassVar[CuranddxOperatorType] = ...
    OUTPUT_TYPE: ClassVar[CuranddxOperatorType] = ...
    PHILOX_ROUNDS: ClassVar[CuranddxOperatorType] = ...
    SM: ClassVar[CuranddxOperatorType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CuranddxTraitType(enum.IntEnum):
    """
    Traits.The set of supported types of traits that can be accessed from
    finalized sources that use curanddx.

    See `curanddxTraitType`.
    """
    __new__: ClassVar[Callable] = ...
    STATE_ALIGNMENT: ClassVar[CuranddxTraitType] = ...
    STATE_SIZE: ClassVar[CuranddxTraitType] = ...
    SYMBOL_DESTROY_STATE_NAME: ClassVar[CuranddxTraitType] = ...
    SYMBOL_GENERATE_NAME: ClassVar[CuranddxTraitType] = ...
    SYMBOL_INIT_STATE_NAME: ClassVar[CuranddxTraitType] = ...
    SYMBOL_SKIP_OFFSET_NAME: ClassVar[CuranddxTraitType] = ...
    SYMBOL_SKIP_SEQUENCE_NAME: ClassVar[CuranddxTraitType] = ...
    SYMBOL_SKIP_SUBSEQUENCE_NAME: ClassVar[CuranddxTraitType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CusolverdxApi(enum.IntEnum):
    """
    Type of cusolverdx API.

    See `cusolverdxApi`.
    """
    __new__: ClassVar[Callable] = ...
    SMEM: ClassVar[CusolverdxApi] = ...
    SMEM_DYNAMIC_LD: ClassVar[CusolverdxApi] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CusolverdxArrangement(enum.IntEnum):
    """
    Data arrangement mode.Defines data arrangements in tensors' taking part
    in the calculation.

    See `cusolverdxArrangement`.
    """
    __new__: ClassVar[Callable] = ...
    COL_MAJOR: ClassVar[CusolverdxArrangement] = ...
    ROW_MAJOR: ClassVar[CusolverdxArrangement] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CusolverdxDiag(enum.IntEnum):
    """
    Diag operator.Indicates whether the matrix diagonal is unit (all ones)
    or non-unit.

    See `cusolverdxDiag`.
    """
    __new__: ClassVar[Callable] = ...
    NON_UNIT: ClassVar[CusolverdxDiag] = ...
    UNIT: ClassVar[CusolverdxDiag] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CusolverdxFillMode(enum.IntEnum):
    """
    Tensor fill mode.For symmetric matrix the fill mode can be upper or
    lower triangular

    See `cusolverdxFillMode`.
    """
    __new__: ClassVar[Callable] = ...
    LOWER: ClassVar[CusolverdxFillMode] = ...
    UPPER: ClassVar[CusolverdxFillMode] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CusolverdxFunction(enum.IntEnum):
    '''
    Type of device function.The function signatures depend on the selected
    cusolverdxApi_t:  - For CUSOLVERDX_API_SMEM: Leading dimensions are
    fixed at compile time.  - For CUSOLVERDX_API_SMEM_DYNAMIC_LD: Leading
    dimensions are passed as pointers to `unsigned` at runtime.  Type
    definitions used in function signatures:  - `value_type`: The value
    type determined by CUSOLVERDX_OPERATOR_TYPE and
    CUSOLVERDX_OPERATOR_PRECISION. For real types: `float` or `double`. For
    complex types: `cuFloatComplex` or `cuDoubleComplex`.  - `status_type`:
    A signed 32b integer (`int`) used to return status information.  All
    functions are `extern "C"` and the symbol name can be queried using
    CUSOLVERDX_TRAIT_SYMBOL_NAME.

    See `cusolverdxFunction`.
    '''
    __new__: ClassVar[Callable] = ...
    GELQF: ClassVar[CusolverdxFunction] = ...
    GELS: ClassVar[CusolverdxFunction] = ...
    GEQRF: ClassVar[CusolverdxFunction] = ...
    GESV_NO_PIVOT: ClassVar[CusolverdxFunction] = ...
    GESV_PARTIAL_PIVOT: ClassVar[CusolverdxFunction] = ...
    GETRF_NO_PIVOT: ClassVar[CusolverdxFunction] = ...
    GETRF_PARTIAL_PIVOT: ClassVar[CusolverdxFunction] = ...
    GETRS_NO_PIVOT: ClassVar[CusolverdxFunction] = ...
    GETRS_PARTIAL_PIVOT: ClassVar[CusolverdxFunction] = ...
    GTSV_NO_PIVOT: ClassVar[CusolverdxFunction] = ...
    HEEV: ClassVar[CusolverdxFunction] = ...
    HTEV: ClassVar[CusolverdxFunction] = ...
    POSV: ClassVar[CusolverdxFunction] = ...
    POTRF: ClassVar[CusolverdxFunction] = ...
    POTRS: ClassVar[CusolverdxFunction] = ...
    TRSM: ClassVar[CusolverdxFunction] = ...
    UNGLQ: ClassVar[CusolverdxFunction] = ...
    UNGQR: ClassVar[CusolverdxFunction] = ...
    UNMLQ: ClassVar[CusolverdxFunction] = ...
    UNMQR: ClassVar[CusolverdxFunction] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CusolverdxJob(enum.IntEnum):
    """
    Job operator.Specifies whether and how eigenvectors are computed and
    stored in eigenvalue operations.

    See `cusolverdxJob`.
    """
    __new__: ClassVar[Callable] = ...
    ALL_VECTORS: ClassVar[CusolverdxJob] = ...
    MULTIPLY_VECTORS: ClassVar[CusolverdxJob] = ...
    NO_VECTORS: ClassVar[CusolverdxJob] = ...
    OVERWRITE_VECTORS: ClassVar[CusolverdxJob] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CusolverdxOperatorType(enum.IntEnum):
    """
    Operators.The set of supported cusolverDx operators.

    See `cusolverdxOperatorType`.
    """
    __new__: ClassVar[Callable] = ...
    API: ClassVar[CusolverdxOperatorType] = ...
    ARRANGEMENT: ClassVar[CusolverdxOperatorType] = ...
    BATCHES_PER_BLOCK: ClassVar[CusolverdxOperatorType] = ...
    BLOCK_DIM: ClassVar[CusolverdxOperatorType] = ...
    DIAG: ClassVar[CusolverdxOperatorType] = ...
    EXECUTION: ClassVar[CusolverdxOperatorType] = ...
    FILL_MODE: ClassVar[CusolverdxOperatorType] = ...
    FUNCTION: ClassVar[CusolverdxOperatorType] = ...
    JOB: ClassVar[CusolverdxOperatorType] = ...
    LEADING_DIMENSION: ClassVar[CusolverdxOperatorType] = ...
    PRECISION: ClassVar[CusolverdxOperatorType] = ...
    SIDE: ClassVar[CusolverdxOperatorType] = ...
    SIZE: ClassVar[CusolverdxOperatorType] = ...
    SM: ClassVar[CusolverdxOperatorType] = ...
    TRANSPOSE_MODE: ClassVar[CusolverdxOperatorType] = ...
    TYPE: ClassVar[CusolverdxOperatorType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CusolverdxSide(enum.IntEnum):
    """
    Side operator.Indicates which side an operator is applied from in
    operations such as matrix multiplication.

    See `cusolverdxSide`.
    """
    __new__: ClassVar[Callable] = ...
    LEFT: ClassVar[CusolverdxSide] = ...
    RIGHT: ClassVar[CusolverdxSide] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CusolverdxTraitType(enum.IntEnum):
    """
    Traits.The set of supported types of traits that can be accessed from
    finalized sources that use cusolverdx.

    See `cusolverdxTraitType`.
    """
    __new__: ClassVar[Callable] = ...
    ARRANGEMENT: ClassVar[CusolverdxTraitType] = ...
    BATCHES_PER_BLOCK: ClassVar[CusolverdxTraitType] = ...
    BLOCK_DIM: ClassVar[CusolverdxTraitType] = ...
    LEADING_DIMENSION: ClassVar[CusolverdxTraitType] = ...
    SHARED_MEMORY_SIZE: ClassVar[CusolverdxTraitType] = ...
    SUGGESTED_BATCHES_PER_BLOCK: ClassVar[CusolverdxTraitType] = ...
    SUGGESTED_BLOCK_DIM: ClassVar[CusolverdxTraitType] = ...
    SUGGESTED_LEADING_DIMENSION: ClassVar[CusolverdxTraitType] = ...
    SYMBOL_NAME: ClassVar[CusolverdxTraitType] = ...
    TYPE: ClassVar[CusolverdxTraitType] = ...
    VALUE_TYPE: ClassVar[CusolverdxTraitType] = ...
    WORKSPACE_SIZE: ClassVar[CusolverdxTraitType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CusolverdxTransposeMode(enum.IntEnum):
    """
    Transpose mode.Indicates inputs or outputs must be considered
    transposed.

    See `cusolverdxTransposeMode`.
    """
    __new__: ClassVar[Callable] = ...
    CONJ_TRANSPOSED: ClassVar[CusolverdxTransposeMode] = ...
    NON_TRANSPOSED: ClassVar[CusolverdxTransposeMode] = ...
    TRANSPOSED: ClassVar[CusolverdxTransposeMode] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class CusolverdxType(enum.IntEnum):
    """
    Type of input values.

    See `cusolverdxType`.
    """
    __new__: ClassVar[Callable] = ...
    COMPLEX: ClassVar[CusolverdxType] = ...
    REAL: ClassVar[CusolverdxType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value2member_map_: ClassVar[dict] = ...

class LibMathDxError(Exception):
    def __init__(self, status) -> Any:
        """LibMathDxError.__init__(self, status)"""
    def __reduce__(self) -> Any:
        """LibMathDxError.__reduce__(self)"""
