# Copyright (c) 2024-2025, NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED.
#
# SPDX-License-Identifier: Apache-2.0

import _cython_3_0_12
import enum
from typing import Any, Callable, ClassVar

__pyx_capi__: dict
__test__: dict
check_status: _cython_3_0_12.cython_function_or_method
commondx_create_code: _cython_3_0_12.cython_function_or_method
commondx_destroy_code: _cython_3_0_12.cython_function_or_method
commondx_get_code_ltoir: _cython_3_0_12.cython_function_or_method
commondx_get_code_ltoir_size: _cython_3_0_12.cython_function_or_method
commondx_get_code_ltoir_sizes: _cython_3_0_12.cython_function_or_method
commondx_get_code_ltoirs: _cython_3_0_12.cython_function_or_method
commondx_get_code_num_ltoirs: _cython_3_0_12.cython_function_or_method
commondx_get_code_option_int64: _cython_3_0_12.cython_function_or_method
commondx_get_code_options_int64s: _cython_3_0_12.cython_function_or_method
commondx_set_code_option_int64: _cython_3_0_12.cython_function_or_method
commondx_set_code_option_str: _cython_3_0_12.cython_function_or_method
commondx_status_to_str: _cython_3_0_12.cython_function_or_method
cublasdx_bind_device_function: _cython_3_0_12.cython_function_or_method
cublasdx_bind_tensor: _cython_3_0_12.cython_function_or_method
cublasdx_create_descriptor: _cython_3_0_12.cython_function_or_method
cublasdx_destroy_descriptor: _cython_3_0_12.cython_function_or_method
cublasdx_finalize_code: _cython_3_0_12.cython_function_or_method
cublasdx_finalize_device_functions: _cython_3_0_12.cython_function_or_method
cublasdx_finalize_tensors: _cython_3_0_12.cython_function_or_method
cublasdx_get_device_function_trait_str: _cython_3_0_12.cython_function_or_method
cublasdx_get_device_function_trait_str_size: _cython_3_0_12.cython_function_or_method
cublasdx_get_ltoir: _cython_3_0_12.cython_function_or_method
cublasdx_get_ltoir_size: _cython_3_0_12.cython_function_or_method
cublasdx_get_tensor_trait_int64: _cython_3_0_12.cython_function_or_method
cublasdx_get_tensor_trait_str: _cython_3_0_12.cython_function_or_method
cublasdx_get_tensor_trait_str_size: _cython_3_0_12.cython_function_or_method
cublasdx_get_trait_int64: _cython_3_0_12.cython_function_or_method
cublasdx_get_trait_int64s: _cython_3_0_12.cython_function_or_method
cublasdx_get_trait_str: _cython_3_0_12.cython_function_or_method
cublasdx_get_trait_str_size: _cython_3_0_12.cython_function_or_method
cublasdx_operator_type_to_str: _cython_3_0_12.cython_function_or_method
cublasdx_set_operator_int64: _cython_3_0_12.cython_function_or_method
cublasdx_set_operator_int64s: _cython_3_0_12.cython_function_or_method
cublasdx_set_option_str: _cython_3_0_12.cython_function_or_method
cublasdx_set_tensor_option_int64: _cython_3_0_12.cython_function_or_method
cublasdx_trait_type_to_str: _cython_3_0_12.cython_function_or_method
cufftdx_create_descriptor: _cython_3_0_12.cython_function_or_method
cufftdx_destroy_descriptor: _cython_3_0_12.cython_function_or_method
cufftdx_finalize_code: _cython_3_0_12.cython_function_or_method
cufftdx_get_knob_int64s: _cython_3_0_12.cython_function_or_method
cufftdx_get_knob_int64size: _cython_3_0_12.cython_function_or_method
cufftdx_get_ltoir: _cython_3_0_12.cython_function_or_method
cufftdx_get_ltoir_size: _cython_3_0_12.cython_function_or_method
cufftdx_get_trait_commondx_data_type: _cython_3_0_12.cython_function_or_method
cufftdx_get_trait_int64: _cython_3_0_12.cython_function_or_method
cufftdx_get_trait_int64s: _cython_3_0_12.cython_function_or_method
cufftdx_get_trait_str: _cython_3_0_12.cython_function_or_method
cufftdx_get_trait_str_size: _cython_3_0_12.cython_function_or_method
cufftdx_operator_type_to_str: _cython_3_0_12.cython_function_or_method
cufftdx_set_operator_int64: _cython_3_0_12.cython_function_or_method
cufftdx_set_operator_int64s: _cython_3_0_12.cython_function_or_method
cufftdx_set_option_str: _cython_3_0_12.cython_function_or_method
cufftdx_trait_type_to_str: _cython_3_0_12.cython_function_or_method
cusolverdx_create_descriptor: _cython_3_0_12.cython_function_or_method
cusolverdx_destroy_descriptor: _cython_3_0_12.cython_function_or_method
cusolverdx_finalize_code: _cython_3_0_12.cython_function_or_method
cusolverdx_get_ltoir: _cython_3_0_12.cython_function_or_method
cusolverdx_get_ltoir_size: _cython_3_0_12.cython_function_or_method
cusolverdx_get_trait_int64: _cython_3_0_12.cython_function_or_method
cusolverdx_get_trait_str: _cython_3_0_12.cython_function_or_method
cusolverdx_get_trait_str_size: _cython_3_0_12.cython_function_or_method
cusolverdx_get_universal_fatbin: _cython_3_0_12.cython_function_or_method
cusolverdx_get_universal_fatbin_size: _cython_3_0_12.cython_function_or_method
cusolverdx_operator_type_to_str: _cython_3_0_12.cython_function_or_method
cusolverdx_set_operator_int64: _cython_3_0_12.cython_function_or_method
cusolverdx_set_operator_int64s: _cython_3_0_12.cython_function_or_method
cusolverdx_set_option_str: _cython_3_0_12.cython_function_or_method
cusolverdx_trait_type_to_str: _cython_3_0_12.cython_function_or_method
get_version: _cython_3_0_12.cython_function_or_method
get_version_ex: _cython_3_0_12.cython_function_or_method

class CommondxCodeContainer(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    FATBIN: ClassVar[CommondxCodeContainer] = ...
    LTOIR: ClassVar[CommondxCodeContainer] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CommondxExecution(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    BLOCK: ClassVar[CommondxExecution] = ...
    THREAD: ClassVar[CommondxExecution] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CommondxOption(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    CODE_CONTAINER: ClassVar[CommondxOption] = ...
    CODE_ISA: ClassVar[CommondxOption] = ...
    EXTRA_NVTRC_ARGS: ClassVar[CommondxOption] = ...
    SYMBOL_NAME: ClassVar[CommondxOption] = ...
    TARGET_SM: ClassVar[CommondxOption] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CommondxPrecision(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    BF16: ClassVar[CommondxPrecision] = ...
    F16: ClassVar[CommondxPrecision] = ...
    F32: ClassVar[CommondxPrecision] = ...
    F64: ClassVar[CommondxPrecision] = ...
    F8_E4M3: ClassVar[CommondxPrecision] = ...
    F8_E5M2: ClassVar[CommondxPrecision] = ...
    I16: ClassVar[CommondxPrecision] = ...
    I32: ClassVar[CommondxPrecision] = ...
    I64: ClassVar[CommondxPrecision] = ...
    I8: ClassVar[CommondxPrecision] = ...
    TF32: ClassVar[CommondxPrecision] = ...
    UI16: ClassVar[CommondxPrecision] = ...
    UI32: ClassVar[CommondxPrecision] = ...
    UI64: ClassVar[CommondxPrecision] = ...
    UI8: ClassVar[CommondxPrecision] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CommondxStatusType(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    COMPILATION_ERROR: ClassVar[CommondxStatusType] = ...
    CUFFT_ERROR: ClassVar[CommondxStatusType] = ...
    INTERNAL_ERROR: ClassVar[CommondxStatusType] = ...
    INVALID_VALUE: ClassVar[CommondxStatusType] = ...
    SUCCESS: ClassVar[CommondxStatusType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CommondxValueType(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    C_16BF: ClassVar[CommondxValueType] = ...
    C_16F: ClassVar[CommondxValueType] = ...
    C_16F2: ClassVar[CommondxValueType] = ...
    C_16I: ClassVar[CommondxValueType] = ...
    C_16UI: ClassVar[CommondxValueType] = ...
    C_32F: ClassVar[CommondxValueType] = ...
    C_32I: ClassVar[CommondxValueType] = ...
    C_32TF: ClassVar[CommondxValueType] = ...
    C_32UI: ClassVar[CommondxValueType] = ...
    C_64F: ClassVar[CommondxValueType] = ...
    C_64I: ClassVar[CommondxValueType] = ...
    C_64UI: ClassVar[CommondxValueType] = ...
    C_8F_E4M3: ClassVar[CommondxValueType] = ...
    C_8F_E5M2: ClassVar[CommondxValueType] = ...
    C_8I: ClassVar[CommondxValueType] = ...
    C_8UI: ClassVar[CommondxValueType] = ...
    R_16BF: ClassVar[CommondxValueType] = ...
    R_16F: ClassVar[CommondxValueType] = ...
    R_16F2: ClassVar[CommondxValueType] = ...
    R_16I: ClassVar[CommondxValueType] = ...
    R_16UI: ClassVar[CommondxValueType] = ...
    R_32F: ClassVar[CommondxValueType] = ...
    R_32I: ClassVar[CommondxValueType] = ...
    R_32TF: ClassVar[CommondxValueType] = ...
    R_32UI: ClassVar[CommondxValueType] = ...
    R_64F: ClassVar[CommondxValueType] = ...
    R_64I: ClassVar[CommondxValueType] = ...
    R_64UI: ClassVar[CommondxValueType] = ...
    R_8F_E4M3: ClassVar[CommondxValueType] = ...
    R_8F_E5M2: ClassVar[CommondxValueType] = ...
    R_8I: ClassVar[CommondxValueType] = ...
    R_8UI: ClassVar[CommondxValueType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CublasdxApi(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    SMEM: ClassVar[CublasdxApi] = ...
    SMEM_DYNAMIC_LD: ClassVar[CublasdxApi] = ...
    TENSORS: ClassVar[CublasdxApi] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CublasdxArrangement(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    COL_MAJOR: ClassVar[CublasdxArrangement] = ...
    ROW_MAJOR: ClassVar[CublasdxArrangement] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CublasdxDeviceFunctionOption(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    COPY_ALIGNMENT: ClassVar[CublasdxDeviceFunctionOption] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CublasdxDeviceFunctionTrait(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    NAME: ClassVar[CublasdxDeviceFunctionTrait] = ...
    SYMBOL: ClassVar[CublasdxDeviceFunctionTrait] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CublasdxDeviceFunctionType(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    AXPBY: ClassVar[CublasdxDeviceFunctionType] = ...
    CLEAR: ClassVar[CublasdxDeviceFunctionType] = ...
    COPY: ClassVar[CublasdxDeviceFunctionType] = ...
    COPY_WAIT: ClassVar[CublasdxDeviceFunctionType] = ...
    EXECUTE: ClassVar[CublasdxDeviceFunctionType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CublasdxFunction(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    MM: ClassVar[CublasdxFunction] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CublasdxOperatorType(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    ALIGNMENT: ClassVar[CublasdxOperatorType] = ...
    API: ClassVar[CublasdxOperatorType] = ...
    ARRANGEMENT: ClassVar[CublasdxOperatorType] = ...
    BLOCK_DIM: ClassVar[CublasdxOperatorType] = ...
    EXECUTION: ClassVar[CublasdxOperatorType] = ...
    FUNCTION: ClassVar[CublasdxOperatorType] = ...
    LEADING_DIMENSION: ClassVar[CublasdxOperatorType] = ...
    PRECISION: ClassVar[CublasdxOperatorType] = ...
    SIZE: ClassVar[CublasdxOperatorType] = ...
    SM: ClassVar[CublasdxOperatorType] = ...
    STATIC_BLOCK_DIM: ClassVar[CublasdxOperatorType] = ...
    TRANSPOSE_MODE: ClassVar[CublasdxOperatorType] = ...
    TYPE: ClassVar[CublasdxOperatorType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CublasdxTensorOption(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    ALIGNMENT_BYTES: ClassVar[CublasdxTensorOption] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CublasdxTensorTrait(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    ALIGNMENT_BYTES: ClassVar[CublasdxTensorTrait] = ...
    OPAQUE_NAME: ClassVar[CublasdxTensorTrait] = ...
    STORAGE_BYTES: ClassVar[CublasdxTensorTrait] = ...
    UID: ClassVar[CublasdxTensorTrait] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CublasdxTensorType(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    GMEM_A: ClassVar[CublasdxTensorType] = ...
    GMEM_B: ClassVar[CublasdxTensorType] = ...
    GMEM_C: ClassVar[CublasdxTensorType] = ...
    SMEM_A: ClassVar[CublasdxTensorType] = ...
    SMEM_B: ClassVar[CublasdxTensorType] = ...
    SMEM_C: ClassVar[CublasdxTensorType] = ...
    SUGGESTED_RMEM_C: ClassVar[CublasdxTensorType] = ...
    SUGGESTED_SMEM_A: ClassVar[CublasdxTensorType] = ...
    SUGGESTED_SMEM_B: ClassVar[CublasdxTensorType] = ...
    SUGGESTED_SMEM_C: ClassVar[CublasdxTensorType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CublasdxTraitType(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    ALIGNMENT: ClassVar[CublasdxTraitType] = ...
    ARRANGEMENT: ClassVar[CublasdxTraitType] = ...
    BLOCK_DIM: ClassVar[CublasdxTraitType] = ...
    BLOCK_SIZE: ClassVar[CublasdxTraitType] = ...
    LEADING_DIMENSION: ClassVar[CublasdxTraitType] = ...
    MAX_THREADS_PER_BLOCK: ClassVar[CublasdxTraitType] = ...
    SIZE: ClassVar[CublasdxTraitType] = ...
    SUGGESTED_BLOCK_DIM: ClassVar[CublasdxTraitType] = ...
    SUGGESTED_LEADING_DIMENSION: ClassVar[CublasdxTraitType] = ...
    SYMBOL_NAME: ClassVar[CublasdxTraitType] = ...
    VALUE_TYPE: ClassVar[CublasdxTraitType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CublasdxTransposeMode(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    CONJ_TRANSPOSED: ClassVar[CublasdxTransposeMode] = ...
    NON_TRANSPOSED: ClassVar[CublasdxTransposeMode] = ...
    TRANSPOSED: ClassVar[CublasdxTransposeMode] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CublasdxType(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    COMPLEX: ClassVar[CublasdxType] = ...
    REAL: ClassVar[CublasdxType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CufftdxApi(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    LMEM: ClassVar[CufftdxApi] = ...
    SMEM: ClassVar[CufftdxApi] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CufftdxCodeType(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    LTOIR: ClassVar[CufftdxCodeType] = ...
    PTX: ClassVar[CufftdxCodeType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CufftdxComplexLayout(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    FULL: ClassVar[CufftdxComplexLayout] = ...
    NATURAL: ClassVar[CufftdxComplexLayout] = ...
    PACKED: ClassVar[CufftdxComplexLayout] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CufftdxDirection(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    FORWARD: ClassVar[CufftdxDirection] = ...
    INVERSE: ClassVar[CufftdxDirection] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CufftdxKnobType(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    ELEMENTS_PER_THREAD: ClassVar[CufftdxKnobType] = ...
    FFTS_PER_BLOCK: ClassVar[CufftdxKnobType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CufftdxOperatorType(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    API: ClassVar[CufftdxOperatorType] = ...
    BLOCK_DIM: ClassVar[CufftdxOperatorType] = ...
    CODE_TYPE: ClassVar[CufftdxOperatorType] = ...
    DIRECTION: ClassVar[CufftdxOperatorType] = ...
    ELEMENTS_PER_THREAD: ClassVar[CufftdxOperatorType] = ...
    EXECUTION: ClassVar[CufftdxOperatorType] = ...
    FFTS_PER_BLOCK: ClassVar[CufftdxOperatorType] = ...
    PRECISION: ClassVar[CufftdxOperatorType] = ...
    REAL_FFT_OPTIONS: ClassVar[CufftdxOperatorType] = ...
    SIZE: ClassVar[CufftdxOperatorType] = ...
    SM: ClassVar[CufftdxOperatorType] = ...
    TYPE: ClassVar[CufftdxOperatorType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CufftdxRealMode(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    FOLDED: ClassVar[CufftdxRealMode] = ...
    NORMAL: ClassVar[CufftdxRealMode] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CufftdxTraitType(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    BLOCK_DIM: ClassVar[CufftdxTraitType] = ...
    ELEMENTS_PER_THREAD: ClassVar[CufftdxTraitType] = ...
    FFTS_PER_BLOCK: ClassVar[CufftdxTraitType] = ...
    IMPLICIT_TYPE_BATCHING: ClassVar[CufftdxTraitType] = ...
    INPUT_ELEMENTS_PER_THREAD: ClassVar[CufftdxTraitType] = ...
    INPUT_LENGTH: ClassVar[CufftdxTraitType] = ...
    INPUT_TYPE: ClassVar[CufftdxTraitType] = ...
    OUTPUT_ELEMENTS_PER_THREAD: ClassVar[CufftdxTraitType] = ...
    OUTPUT_LENGTH: ClassVar[CufftdxTraitType] = ...
    OUTPUT_TYPE: ClassVar[CufftdxTraitType] = ...
    SHARED_MEMORY_SIZE: ClassVar[CufftdxTraitType] = ...
    STORAGE_SIZE: ClassVar[CufftdxTraitType] = ...
    STRIDE: ClassVar[CufftdxTraitType] = ...
    SUGGESTED_FFTS_PER_BLOCK: ClassVar[CufftdxTraitType] = ...
    SYMBOL_NAME: ClassVar[CufftdxTraitType] = ...
    VALUE_TYPE: ClassVar[CufftdxTraitType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CufftdxType(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    C2C: ClassVar[CufftdxType] = ...
    C2R: ClassVar[CufftdxType] = ...
    R2C: ClassVar[CufftdxType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CusolverdxApi(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    SMEM: ClassVar[CusolverdxApi] = ...
    SMEM_DYNAMIC_LD: ClassVar[CusolverdxApi] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CusolverdxArrangement(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    COL_MAJOR: ClassVar[CusolverdxArrangement] = ...
    ROW_MAJOR: ClassVar[CusolverdxArrangement] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CusolverdxDiag(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    NON_UNIT: ClassVar[CusolverdxDiag] = ...
    UNIT: ClassVar[CusolverdxDiag] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CusolverdxFillMode(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    LOWER: ClassVar[CusolverdxFillMode] = ...
    UPPER: ClassVar[CusolverdxFillMode] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CusolverdxFunction(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    GETRF_NO_PIVOT: ClassVar[CusolverdxFunction] = ...
    GETRS_NO_PIVOT: ClassVar[CusolverdxFunction] = ...
    POTRF: ClassVar[CusolverdxFunction] = ...
    POTRS: ClassVar[CusolverdxFunction] = ...
    TRSM: ClassVar[CusolverdxFunction] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CusolverdxOperatorType(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    API: ClassVar[CusolverdxOperatorType] = ...
    ARRANGEMENT: ClassVar[CusolverdxOperatorType] = ...
    BLOCK_DIM: ClassVar[CusolverdxOperatorType] = ...
    DIAG: ClassVar[CusolverdxOperatorType] = ...
    EXECUTION: ClassVar[CusolverdxOperatorType] = ...
    FILL_MODE: ClassVar[CusolverdxOperatorType] = ...
    FUNCTION: ClassVar[CusolverdxOperatorType] = ...
    PRECISION: ClassVar[CusolverdxOperatorType] = ...
    SIDE: ClassVar[CusolverdxOperatorType] = ...
    SIZE: ClassVar[CusolverdxOperatorType] = ...
    SM: ClassVar[CusolverdxOperatorType] = ...
    TYPE: ClassVar[CusolverdxOperatorType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CusolverdxSide(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    LEFT: ClassVar[CusolverdxSide] = ...
    RIGHT: ClassVar[CusolverdxSide] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CusolverdxTraitType(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    SHARED_MEMORY_SIZE: ClassVar[CusolverdxTraitType] = ...
    SYMBOL_NAME: ClassVar[CusolverdxTraitType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class CusolverdxType(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    COMPLEX: ClassVar[CusolverdxType] = ...
    REAL: ClassVar[CusolverdxType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class LibMathDxError(Exception):
    def __init__(self, status) -> Any: ...
    def __reduce__(self) -> Any: ...
