# Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED.
#
# SPDX-License-Identifier: Apache-2.0

"""
This example demonstrates usage of epilogs that use auxiliary output generated from a
previous matmul operation.

In this example we'll use the GELU_AUX epilog, which generates an extra output "gelu_aux".
The auxiliary output in this case represent the input to the GELU function. In general,
auxiliary output should be considered opaque, and is meant to be generated by one matmul
operation and used in another with a compatible epilog.

Here we generate the auxiliary output in a forward pass using GELU, and provide it as epilog
input in the corresponding backward pass using the DGELU epilog.

$ mpiexec -n 4 python example08_epilog_dgelu.py
"""

import cupy as cp
from mpi4py import MPI

import nvmath.distributed
from nvmath.distributed.distribution import Slab

# Initialize nvmath.distributed.
comm = MPI.COMM_WORLD
rank = comm.Get_rank()
nranks = comm.Get_size()
device_id = rank % cp.cuda.runtime.getDeviceCount()
# cuBLASMp requires NCCL communication backend.
nvmath.distributed.initialize(device_id, comm, backends=["nccl"])

# Prepare sample input data.
m, n, k = 128, 256, 512

row_wise_distribution = Slab.X
col_wise_distribution = Slab.Y

with cp.cuda.Device(device_id):
    a = cp.random.rand(*col_wise_distribution.shape(rank, (k, m)))
    b = cp.random.rand(*row_wise_distribution.shape(rank, (n, k)))

# Get a transposed view to obtain column-major memory layout. Note that this
# also changes the distribution of a and b (see example01 for more information).
a = a.T  # a is now (m, k) with row_wise_distribution
b = b.T  # b is now (k, n) with col_wise_distribution

# Distributions for A, B, and result matrix D
distributions = [row_wise_distribution, col_wise_distribution, row_wise_distribution]

# Perform the multiplication with GELU_AUX epilog (forward pass).
epilog = nvmath.distributed.linalg.advanced.MatmulEpilog.GELU_AUX
result, auxiliary = nvmath.distributed.linalg.advanced.matmul(
    a,
    b,
    distributions=distributions,
    epilog=epilog,
)

# Note: GELU_AUX output has the same distribution as the result matrix.
assert auxiliary["gelu_aux"].shape == row_wise_distribution.shape(rank, (m, n)) == result.shape

# In the backward pass using DGELU epilog, provide the auxiliary output as epilog input.
epilog = nvmath.distributed.linalg.advanced.MatmulEpilog.DGELU
result = nvmath.distributed.linalg.advanced.matmul(
    a,
    b,
    distributions=distributions,
    epilog=epilog,
    epilog_inputs=auxiliary,
)

# Synchronize the default stream, since by default the execution is non-blocking for GPU
# operands.
cp.cuda.get_current_stream().synchronize()
if rank == 0:
    print(
        f"Inputs were of types {type(a)} and {type(b)}, and the result type is {type(result)}, "
        f"and the auxiliary output is of type {type(auxiliary)}."
    )
